New toLocalDateRange method in Year, YearMonth, YearMonthRange and YearWeek classes
brick/date-time pull request #46
Opened 2022-04-09 12:40 UTC by solodkiy

New methods:

- `Year::toLocalDateRange`
- `YearMonth::toLocalDateRange`
- `YearMonthRange::toLocalDateRange`
- `YearWeek::toLocalDateRange`

2022-05-29 21:50 UTC, BenMorel requested changes

2022-05-29 21:50 UTC, BenMorel commented on tests/YearWeekTest.php
> +        $expectedDareRange = LocalDateRange::parse($firstDay . '/' . $lastDay);
`expectedDateRange`

2022-05-29 21:50 UTC, BenMorel commented on tests/YearWeekTest.php
> +        $this->assertEquals($expectedDareRange, $yearWeek->toLocalDateRange());
Could you please compare their string representations instead of loosely comparing objects?

2022-05-29 21:51 UTC, BenMorel commented
LGTM :+1: Please fix the nitpicks & let's merge!

2022-05-30 06:35 UTC, solodkiy commented
Done

2022-05-30 21:46 UTC, merged

2022-05-30 21:47 UTC, BenMorel commented
Thanks, @solodkiy!