Add Native prefix (Period, TimeZone)
brick/date-time pull request #52
Opened 2022-06-06 19:25 UTC by solodkiy

- Period::fromNativeDateInterval 
- Period::toNativeDateInterval
- TimeZone::fromNativeDateTimeZone
- TimeZone::toNativeDateTimeZone

2022-06-06 21:03 UTC, BenMorel requested changes

2022-06-06 21:05 UTC, BenMorel commented
Thank you, do you want to convert other methods in separate PRs? In this case, please fixup the [skip psalm check](https://github.com/brick/date-time/pull/52/commits/af66b6d7687364caf178302f7cb2d9ed90f851f9) commit onto the correct commit to keep a clean history, as I won't squash those.

2022-06-07 06:46 UTC, solodkiy commented on tests/PeriodTest.php
> +        $this->assertEquals($period, $legacyPeriod);
Ok

2022-06-11 22:22 UTC, merged

2022-06-11 22:23 UTC, BenMorel commented
Thank you, @solodkiy!