Bring back support for sub-minute offsets in PHP >= 8.1.7
brick/date-time pull request #60
Opened 2022-06-19 18:52 UTC by jiripudil

closes #44

2023-05-19 23:01 UTC, BenMorel requested changes
Thanks a lot for the quality work, and sorry for the delay @jiripudil!
Just a couple nitpicks and I'll merge it :+1:

2023-05-19 23:01 UTC, BenMorel commented on tests/ZonedDateTimeTest.php
> -            ['2001-02-03T01:02:03.456+12:34:56'],
Could you please keep this test for PHP < 8.1.7, as you've done for other tests?

2023-05-19 23:08 UTC, BenMorel commented
By the way, regarding the workaround for `DateTimeZone::getName()` omitting seconds, I created an issue with PHP:

https://github.com/php/php-src/issues/11281

2023-06-18 14:40 UTC, jiripudil commented
Hi, thanks, I've fixed the nitpicks and rebased the branch.

Also it seems that the issue has been fixed already (https://github.com/php/php-src/commit/f9117eb82487a0566c8fee3fda798cc2eb969d4a), so I've updated the workaround to only apply in affected PHP versions.

2023-06-20 10:29 UTC, BenMorel approved these changes

2023-06-20 10:29 UTC, merged

2023-06-20 10:29 UTC, BenMorel commented
Thank you, @jiripudil !