Add ZonedDateTime::getDurationTo method
brick/date-time pull request #71
Opened 2023-07-02 11:11 UTC by solodkiy

Just more convenient way to get Duration between two ZonedDateTime

```php
$duration = Duration::between($first->getInstant(), $second->getInstant());
->
$duration = $first->getDurationTo($second);

```

2023-07-17 20:57 UTC, BenMorel requested changes

2023-07-17 20:57 UTC, BenMorel commented on tests/ZonedDateTimeTest.php
> +        $this->assertEquals($expectedResult, $actualResult);
Can you please use `assertDurationIs()`?

2023-07-17 20:57 UTC, BenMorel commented on src/ZonedDateTime.php
> +    public function getDurationTo(ZonedDateTime $secondZonedDateTime): Duration
Please use `$that` for consistency with the rest of the codebase!

2023-07-17 20:57 UTC, BenMorel commented on src/ZonedDateTime.php
> +     */
```suggestion
    /**
     * Returns a Duration representing the time elapsed between this ZonedDateTime and the given one.
     * This method will return a negative duration if the given ZonedDateTime is before the current one.
     */
```

2023-07-17 20:58 UTC, BenMorel commented
A few nitpicks, otherwise LGTM @solodkiy!

2023-07-22 20:24 UTC, solodkiy commented
@BenMorel 
Resolved

2023-07-23 18:21 UTC, merged

2023-08-01 09:21 UTC, BenMorel commented
Released in [0.5.1](https://github.com/brick/date-time/releases/tag/0.5.1)!